Repository brain-tec/manufacture, pull requests merged in 2024-07, with the labels that each got.

#1133 Syncing from upstream OCA/manufacture (14.0)
  README.md
  mrp_production_back_to_draft/README.rst
  mrp_production_back_to_draft/__init__.py
  mrp_production_back_to_draft/__manifest__.py
  mrp_production_back_to_draft/i18n/mrp_production_back_to_draft.pot
  mrp_production_back_to_draft/models/__init__.py
  mrp_production_back_to_draft/models/mrp_production.py
  mrp_production_back_to_draft/readme/CONTRIBUTORS.rst
  mrp_production_back_to_draft/readme/DESCRIPTION.rst
  mrp_production_back_to_draft/static/description/icon.png
  mrp_production_back_to_draft/static/description/index.html
  mrp_production_back_to_draft/tests/__init__.py
  mrp_production_back_to_draft/tests/test_mrp_return_to_draft.py
  mrp_production_back_to_draft/views/mrp_production_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/mrp_production_back_to_draft/odoo/addons/mrp_production_back_to_draft
  setup/mrp_production_back_to_draft/setup.py
Labels: 14.0

#1134 Syncing from upstream OCA/manufacture (16.0)
  mrp_bom_note/i18n/de.po
  mrp_bom_note/i18n/es.po
  mrp_bom_note/i18n/fi.po
  mrp_bom_note/i18n/fr.po
  mrp_bom_note/i18n/gl.po
  mrp_bom_note/i18n/hr.po
  mrp_bom_note/i18n/hr_HR.po
  mrp_bom_note/i18n/it.po
  mrp_bom_note/i18n/lt.po
  mrp_bom_note/i18n/nl_NL.po
  mrp_bom_note/i18n/pt_BR.po
  mrp_bom_note/i18n/ro.po
  mrp_bom_note/i18n/sl.po
  mrp_bom_note/i18n/tr.po
  mrp_bom_note/i18n/tr_TR.po
  mrp_bom_note/i18n/zh_CN.po
Labels: 16.0

#1135 Syncing from upstream OCA/manufacture (16.0)
  mrp_lot_number_propagation/i18n/it.po
Labels: 16.0

#1136 Syncing from upstream OCA/manufacture (16.0)
  mrp_bom_note/i18n/pt_BR.po
Labels: 16.0

#1137 Syncing from upstream OCA/manufacture (16.0)
  README.md
  mrp_bom_image/README.rst
  mrp_bom_image/__init__.py
  mrp_bom_image/__manifest__.py
  mrp_bom_image/i18n/mrp_bom_image.pot
  mrp_bom_image/models/__init__.py
  mrp_bom_image/models/mrp_bom.py
  mrp_bom_image/readme/DESCRIPTION.rst
  mrp_bom_image/static/description/icon.png
  mrp_bom_image/static/description/index.html
  mrp_bom_image/static/description/mrp_bom_image.png
  mrp_bom_image/static/description/mrp_bom_image_kanban.png
  mrp_bom_image/views/view_mrp_bom.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/mrp_bom_image/odoo/addons/mrp_bom_image
  setup/mrp_bom_image/setup.py
Labels: 16.0

#1138 Syncing from upstream OCA/manufacture (16.0)
  README.md
  mrp_bom_image/i18n/it.po
  mrp_multi_level/README.rst
  mrp_multi_level/__manifest__.py
  mrp_multi_level/i18n/de.po
  mrp_multi_level/i18n/es.po
  mrp_multi_level/i18n/hr.po
  mrp_multi_level/i18n/it.po
  mrp_multi_level/i18n/mrp_multi_level.pot
  mrp_multi_level/models/stock_location.py
  mrp_multi_level/static/description/index.html
  mrp_multi_level/views/stock_location_views.xml
  quality_control_oca/i18n/ja.po
Labels: 16.0

#1139 Syncing from upstream OCA/manufacture (15.0)
  mrp_sale_info/i18n/de.po
  mrp_sale_info/i18n/es.po
  mrp_sale_info/i18n/fr.po
  mrp_sale_info/i18n/it.po
  mrp_sale_info/i18n/mrp_sale_info.pot
  mrp_sale_info/i18n/pt_BR.po
  mrp_sale_info/i18n/zh_CN.po
  mrp_sale_info/models/__init__.py
  mrp_sale_info/models/sale_order_line.py
  mrp_sale_info/models/stock_move.py
  mrp_sale_info/tests/test_mrp_sale_info.py
Labels: 15.0

#1141 Syncing from upstream OCA/manufacture (8.0)
  mrp_calendar_view/i18n/it.po
Labels: 8.0

#1142 Syncing from upstream OCA/manufacture (10.0)
  mrp_repair_calendar_view/i18n/it.po
Labels: 10.0

#1143 Syncing from upstream OCA/manufacture (12.0)
  base_repair/i18n/it.po
  repair_calendar_view/i18n/it.po
Labels: 12.0

#1144 Syncing from upstream OCA/manufacture (14.0)
  base_repair/i18n/it.po
Labels: 14.0

#1145 Syncing from upstream OCA/manufacture (15.0)
  README.md
  mrp_multi_level/README.rst
  mrp_multi_level/__manifest__.py
  mrp_multi_level/static/description/index.html
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: 15.0

#1146 Syncing from upstream OCA/manufacture (16.0)
  README.md
  mrp_multi_level/README.rst
  mrp_multi_level/__manifest__.py
  mrp_multi_level/static/description/index.html
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: 16.0

#1147 Syncing from upstream OCA/manufacture (17.0)
  README.md
  mrp_multi_level/README.rst
  mrp_multi_level/__manifest__.py
  mrp_multi_level/static/description/index.html
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: 17.0

#1148 Syncing from upstream OCA/manufacture (16.0)
  README.md
  mrp_bom_tag/README.rst
  mrp_bom_tag/__init__.py
  mrp_bom_tag/__manifest__.py
  mrp_bom_tag/demo/mrp_bom_tag.xml
  mrp_bom_tag/i18n/fr.po
  mrp_bom_tag/i18n/mrp_bom_tag.pot
  mrp_bom_tag/models/__init__.py
  mrp_bom_tag/models/mrp_bom.py
  mrp_bom_tag/models/mrp_bom_tag.py
  mrp_bom_tag/readme/CONFIGURE.rst
  mrp_bom_tag/readme/CONTRIBUTORS.rst
  mrp_bom_tag/readme/DESCRIPTION.rst
  mrp_bom_tag/security/ir.model.access.csv
  mrp_bom_tag/security/ir_rule.xml
  mrp_bom_tag/static/description/bom_tag_configuration.png
  mrp_bom_tag/static/description/bom_with_tag.png
  mrp_bom_tag/static/description/icon.png
  mrp_bom_tag/static/description/index.html
  mrp_bom_tag/tests/__init__.py
  mrp_bom_tag/tests/test_bom_tag.py
  mrp_bom_tag/views/view_mrp_bom.xml
  mrp_bom_tag/views/view_mrp_bom_tag.xml
  mrp_multi_level/README.rst
  mrp_multi_level/__manifest__.py
  mrp_multi_level/static/description/index.html
  mrp_multi_level/wizards/mrp_multi_level.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/mrp_bom_tag/odoo/addons/mrp_bom_tag
  setup/mrp_bom_tag/setup.py
Labels: 16.0

#1149 Syncing from upstream OCA/manufacture (17.0)
  README.md
  mrp_multi_level/README.rst
  mrp_multi_level/__manifest__.py
  mrp_multi_level/static/description/index.html
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: 17.0

#1150 [t150539] 17.0.mig mrp bom attribute match
  mrp_bom_attribute_match/README.rst
  mrp_bom_attribute_match/__init__.py
  mrp_bom_attribute_match/__manifest__.py
  mrp_bom_attribute_match/i18n/es.po
  mrp_bom_attribute_match/i18n/hr.po
  mrp_bom_attribute_match/i18n/it.po
  mrp_bom_attribute_match/i18n/mrp_bom_attribute_match.pot
  mrp_bom_attribute_match/models/__init__.py
  mrp_bom_attribute_match/models/mrp_bom.py
  mrp_bom_attribute_match/models/mrp_production.py
  mrp_bom_attribute_match/models/product.py
  mrp_bom_attribute_match/pyproject.toml
  mrp_bom_attribute_match/readme/CONTRIBUTORS.md
  mrp_bom_attribute_match/readme/DESCRIPTION.md
  mrp_bom_attribute_match/readme/USAGE.md
  mrp_bom_attribute_match/reports/__init__.py
  mrp_bom_attribute_match/reports/mrp_report_bom_structure.py
  mrp_bom_attribute_match/static/description/icon.png
  mrp_bom_attribute_match/static/description/index.html
  mrp_bom_attribute_match/tests/__init__.py
  mrp_bom_attribute_match/tests/common.py
  mrp_bom_attribute_match/tests/test_mrp_bom_attribute_match.py
  mrp_bom_attribute_match/views/mrp_bom_views.xml
Labels: 17.0.project_ty_749

#1152 Syncing from upstream OCA/manufacture (17.0)
  README.md
  mrp_production_note/README.rst
  mrp_production_note/__init__.py
  mrp_production_note/__manifest__.py
  mrp_production_note/i18n/de.po
  mrp_production_note/i18n/es.po
  mrp_production_note/i18n/es_MX.po
  mrp_production_note/i18n/fi.po
  mrp_production_note/i18n/fr.po
  mrp_production_note/i18n/gl.po
  mrp_production_note/i18n/hr.po
  mrp_production_note/i18n/hr_HR.po
  mrp_production_note/i18n/it.po
  mrp_production_note/i18n/lt.po
  mrp_production_note/i18n/mrp_production_note.pot
  mrp_production_note/i18n/nl_NL.po
  mrp_production_note/i18n/pt_BR.po
  mrp_production_note/i18n/ro.po
  mrp_production_note/i18n/sl.po
  mrp_production_note/i18n/tr.po
  mrp_production_note/i18n/tr_TR.po
  mrp_production_note/i18n/vi_VN.po
  mrp_production_note/i18n/zh_CN.po
  mrp_production_note/models/__init__.py
  mrp_production_note/models/mrp_production.py
  mrp_production_note/pyproject.toml
  mrp_production_note/readme/CONTRIBUTORS.md
  mrp_production_note/readme/DESCRIPTION.md
  mrp_production_note/readme/USAGE.md
  mrp_production_note/static/description/icon.png
  mrp_production_note/static/description/index.html
  mrp_production_note/views/mrp_production_view.xml
  setup/_metapackage/pyproject.toml
Labels: 17.0

#1153 Syncing from upstream OCA/manufacture (14.0)
  README.md
  mrp_component_operation/README.rst
  mrp_component_operation/__manifest__.py
  mrp_component_operation/i18n/es.po
  mrp_component_operation/i18n/it.po
  mrp_component_operation/i18n/mrp_component_operation.pot
  mrp_component_operation/models/mrp_component_operation.py
  mrp_component_operation/static/description/index.html
  mrp_component_operation/views/mrp_component_operation_views.xml
Labels: 14.0

#1154 Syncing from upstream OCA/manufacture (16.0)
  README.md
  mrp_multi_level/README.rst
  mrp_multi_level/__manifest__.py
  mrp_multi_level/models/product_mrp_area.py
  mrp_multi_level/static/description/index.html
  mrp_multi_level/wizards/mrp_multi_level.py
  quality_control_mrp_oca/README.rst
  quality_control_mrp_oca/__init__.py
  quality_control_mrp_oca/__manifest__.py
  quality_control_mrp_oca/data/quality_control_mrp_data.xml
  quality_control_mrp_oca/i18n/ca.po
  quality_control_mrp_oca/i18n/de.po
  quality_control_mrp_oca/i18n/el_GR.po
  quality_control_mrp_oca/i18n/es.po
  quality_control_mrp_oca/i18n/es_ES.po
  quality_control_mrp_oca/i18n/es_MX.po
  quality_control_mrp_oca/i18n/eu.po
  quality_control_mrp_oca/i18n/fi.po
  quality_control_mrp_oca/i18n/fr.po
  quality_control_mrp_oca/i18n/fr_CH.po
  quality_control_mrp_oca/i18n/fr_FR.po
  quality_control_mrp_oca/i18n/gl.po
  quality_control_mrp_oca/i18n/hr.po
  quality_control_mrp_oca/i18n/hr_HR.po
  quality_control_mrp_oca/i18n/it.po
  quality_control_mrp_oca/i18n/nl.po
  quality_control_mrp_oca/i18n/nl_NL.po
  quality_control_mrp_oca/i18n/pt.po
  quality_control_mrp_oca/i18n/pt_BR.po
  quality_control_mrp_oca/i18n/quality_control_mrp_oca.pot
  quality_control_mrp_oca/i18n/ro.po
  quality_control_mrp_oca/i18n/ru.po
  quality_control_mrp_oca/i18n/sk.po
  quality_control_mrp_oca/i18n/sl.po
  quality_control_mrp_oca/i18n/tr.po
  quality_control_mrp_oca/i18n/tr_TR.po
  quality_control_mrp_oca/i18n/vi_VN.po
  quality_control_mrp_oca/i18n/zh_CN.po
  quality_control_mrp_oca/models/__init__.py
  quality_control_mrp_oca/models/mrp_production.py
  quality_control_mrp_oca/models/qc_inspection.py
  quality_control_mrp_oca/readme/CONTRIBUTORS.rst
  quality_control_mrp_oca/readme/DESCRIPTION.rst
  quality_control_mrp_oca/static/description/icon.png
  quality_control_mrp_oca/static/description/index.html
  quality_control_mrp_oca/tests/__init__.py
  quality_control_mrp_oca/tests/test_quality_control_mrp.py
  quality_control_mrp_oca/views/mrp_production_view.xml
  quality_control_mrp_oca/views/qc_inspection_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/quality_control_mrp_oca/odoo/addons/quality_control_mrp_oca
  setup/quality_control_mrp_oca/setup.py
Labels: 16.0

#1155 Syncing from upstream OCA/manufacture (15.0)
  README.md
  mrp_multi_level/README.rst
  mrp_multi_level/__manifest__.py
  mrp_multi_level/models/product_mrp_area.py
  mrp_multi_level/static/description/index.html
  mrp_multi_level/wizards/mrp_multi_level.py
Labels: 15.0

#1156 Syncing from upstream OCA/manufacture (16.0)
  README.md
  mrp_bom_tag/i18n/it.po
  mrp_multi_level/README.rst
  mrp_multi_level/__manifest__.py
  mrp_multi_level/models/product_mrp_area.py
  mrp_multi_level/static/description/index.html
Labels: 16.0
